@echo off
echo Setting up Django backend...

echo Installing requirements...
pip install -r requirements.txt

echo Making migrations...
python manage.py makemigrations

echo Running migrations...
python manage.py migrate

echo Creating superuser (optional)...
echo You can create a superuser by running: python manage.py createsuperuser

echo Starting Django server...
python manage.py runserver